name: Build

on: [push, pull_request]

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build library
        run: dotnet pack -c Release
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: nuget-${{ matrix.os }}
          path: |
            bin/**/*.nupkg
          if-no-files-found: error
  deploy:
    name: deploy-nightly
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.event_name == 'push' }}
    permissions:
      packages: write
    steps:
      - name: Download NuGet artifacts from Ubuntu
        uses: actions/download-artifact@v3
        with:
          name: nuget-ubuntu-latest
          path: nuget-ubuntu
      - name: Push packages
        run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



